### ISSUE TITLE
How to log user out?

### ISSUE THREAD

**Issue by aedensixty** [hapijs/hapi-auth-basic#50]
How do you log out a previously authenticated user?

**Comment by mtharrison** [comment]
There's not really the direct concept of being "logged in" with basic auth like there is with cookie auth. What you're seeing (let me know if I'm wrong) is probably the browser "remembering" your username and password on first entry and submitting them on subsequent requests to save you the hassle of typing them over and over again.

Because basic auth wasn't designed for sessions, it's not obvious, but _there is a way_ to force the browser to purge its cache of the credentials. That's by serving up a `401 Unauthorized` response to their next request (possibly a /logout route). 

Example:

```js
server.route({
    method: 'GET',
    path: '/logout',
    handler: function (request, reply) {

        reply('You are logged out now').code(401);
    }
});
```
Note this isn't a restriction of hapi, it's just [how HTTP basic auth works](http://stackoverflow.com/questions/233507/how-to-log-out-user-from-web-site-using-basic-authentication).

**Comment by aedensixty** [comment]
Great. Worked perfectly. Cheers.

**Comment by seuaCoder** [comment]
I come from php world and currently learning Hap, what Hapi auth plugin is designed for session ? Even the cookie auth store everything in the cookie.
